language: python

python:
  - "3.7"
# command to install dependencies
install:
  - pip install --upgrade setuptools
  - python -m pip install -r requirements.txt

before_script:
  - python mysite/manage.py migrate

# command to run tests
script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls mysite/manage.py test polls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "GQWgii1fhNGkcw86jxkfg0lRjl3cUxFA1e/AZnoxLx0IvIoJsYnRcchhoIrL9TGM/obcXTTBkeaDcEHZ4/4BX4I2c5hxPoJI0Drjjg6+kSurXQ/Qc+UjgtJljsWFZeO57BOK8XUoWxoBqXaPr5nC3I9i3GnGZWuTZKQQQE9SH3zVHNyWy2WsLAvB17P8sVMiOj3e8fLnedpLaXvbxp7bnCaViS8Ii/74uUcoOSpBJ0WdulTlyOTwX+yIJ+wiLZ27UhW8I4Tjru2bw9MA5KlPPS4VwtrCZ/rCr79KA7GrMDzkbxSs3OvADp6GIj0Hod5zRTcZrUqIEbVxuns92k+7oWW/uXDoTAQywXSOvzicf0k76RZBxsrop1JFcbkPrART3RREARVdvNL5oMLrnD8rP3hPe49dUMWjmtHm+yo+bpvbqI70xFr+CUZkFWQ6ARhj6nfDLToQifL6XdKy/kjBL1ZVeqssT9X4DIr6+cOzEJh0uqGR2HyzVQ1zesK8l7roBR4PN+eOe0i2WMdVIAsLzNZxgQkGWasU5EtOXwO0v4XgHpd7WuZSZhbTFlYwXXS7Qt3D98byvtEmCgHRNP2g6+LcjGEvadkHrQQDuVc6OLH67tt7soQ/nAUvv/0SosAGiuJEjrudxJdyfw8HKp0s2hw20emk0xqiCgjh877xRn0="
  secret_access_key:
    secure: "mtVJHQGYmmjye5ag5A6gR4vsF4t0PdLrNE96gT9IrZ1Y4uU0P7yIL6P64qrZCnj1vaImm6hzwSCLBDyqSsy3ED4UqThV6X366dTeeIEGhny8RPCwVoJAjV/k4rDiWP15eKvyGvBfNzSa8myc7F69d77pBsHf8945ceHxPJR4xUWiZLFcv+Wf+q/byb3RY9CiiuI3wI2m1L7ikkrtDuMWgmrHMP2kgfmezlFjT49Pe/cv2oz5pkRqeAy/EWcwviHarSWP1Nxh1ecMvHxGWv6MnLrlTisemH3oIz8AVjPVOBdQFkiQ1G48qSWMH9ceWLGzX7Hi+d88hXQuTEBviIbxd8dwXCY5SB67MvZHZ6BVBH0RFrAZZMgfk4nk/q5Uqkxib+YAJBIYcyO6cM5QDBrZ1SIplyh+xBmo0QXZX/O3s03xc/X+RSOp2QqePbDhzmiuTuxf/yo4JfSNe+xQEd61Z11DfJiHrKOUlpxQT8RT6xw1UOkcM/lj+gcwms3N6tvAAHirWkc7Z6/kkwrmu6GkOcfZ0AIlM53IwwvBvLqzkBOWWjTW2+do+NcdSXVbIdN4Ol81rg1eaO0Zy8mfuup6jKvhg/uAQNaA8ILfr0urBaeulmoXRvmhmqIPqVjb5/2JOHdUinwpqVt89GPI4NktOfhML8rNNRskcZbRsTq7wFM="
  region: "us-east-1"
  app: "django-setup-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-east-1-333633771505"


  after_script:
  - coveralls